framework:
    messenger:
        transports:
            order_queue: '%env(MESSENGER_TRANSPORT_DSN)%/order_queue'
            warehouse_queue: '%env(MESSENGER_TRANSPORT_DSN)%/warehouse_queue'
            receipt_queue: '%env(MESSENGER_TRANSPORT_DSN)%/receipt_queue'
        routing:
            'App\Message\OrderMessage': order_queue
            'App\Message\WarehouseNotificationMessage': warehouse_queue
            'App\Message\ReceiptMessage': receipt_queue
